application: quote-tracker
version: 1
runtime: python
api_version: 1

builtins:
- datastore_admin: on

handlers:
- url: /
  script: index.py

- url: /css
  static_dir: css

- url: /news
  script: news-list.py

- url: /news.ics
  script: news-calendar.py

#- url: /clean-cot
#  script: clean-cot.py

- url: /fetch-cot
  script: fetch-cot.py

- url: /fetch-news
  script: fetch-news.py

- url: /fetch-cot-year
  script: fetch-cot-year.py

- url: /cot-list
  script: cot-list.py

- url: /cot/(.+)
  script: get-cot.py
