application: quote-tracker
version: 1
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: css

- url: /instruments/?(.+)?
  script: instruments-form

- url: /fetch-quotes
  script: fetch-quotes

- url: /settings
  script: settings-form

