application: quote-tracker
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  script: index

- url: /css
  static_dir: css

- url: /instruments/?(.+)?
  script: instruments-form

- url: /fetch-quotes
  script: fetch-quotes

- url: /news
  script: news-list

- url: /update
  script: update

- url: /clean-cot
  script: clean-cot

- url: /fetch-cot
  script: fetch-cot

- url: /fetch-news
  script: fetch-news

- url: /fetch-cot-year
  script: fetch-cot-year

- url: /settings
  script: settings-form

- url: /quotes/(.+)
  script: get-quotes

- url: /cot-list
  script: cot-list

- url: /cot/(.+)
  script: get-cot

- url: /fetch-fx
  script: fetch-fx

# dangerous url, should be commented in production
#- url: /reset-fx
#  script: reset-fx
