application: quote-tracker
version: 1
runtime: python
api_version: 1

builtins:
- datastore_admin: on

handlers:
- url: /
  script: index

- url: /css
  static_dir: css

- url: /news
  script: news-list

- url: /news.ics
  script: news-calendar

- url: /clean-cot
  script: clean-cot

- url: /fetch-cot
  script: fetch-cot

- url: /fetch-news
  script: fetch-news

- url: /fetch-cot-year
  script: fetch-cot-year

- url: /cot-list
  script: cot-list

- url: /cot/(.+)
  script: get-cot
